"""Relative promotion policy for replacing the active strategy.

Absolute research gates and production promotion answer different questions.
This module compares a candidate with the incumbent on one frozen market slice
and records an auditable override without rewriting any raw holdout result.
"""

from __future__ import annotations

import logging
import math
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Mapping

import yaml

logger = logging.getLogger(__name__)

DEFAULT_POLICY_PATH = Path("config/promotion_policy.yaml")


@dataclass(frozen=True)
class PromotionPolicy:
    """Configurable relative performance and safety thresholds."""

    enabled: bool = True
    auto_activate_if_better: bool = True
    minimum_portfolio_return_improvement_pct: float = 0.0
    minimum_improved_groups: int = 2
    maximum_group_return_regression_pct: float = 5.0
    maximum_drawdown_regression_pct: float = 5.0
    safety_max_drawdown_pct: float = -40.0
    minimum_trade_count: int = 1
    minimum_benchmark_count: int = 3
    required_group_count: int = 3

    @classmethod
    def load(cls, path: Path | str = DEFAULT_POLICY_PATH) -> PromotionPolicy:
        policy_path = Path(path)
        try:
            raw = yaml.safe_load(policy_path.read_text(encoding="utf-8")) or {}
        except OSError:
            raw = {}
        if not isinstance(raw, dict):
            raise ValueError("promotion policy must be a mapping")
        return cls(
            enabled=bool(raw.get("enabled", True)),
            auto_activate_if_better=bool(raw.get("auto_activate_if_better", True)),
            minimum_portfolio_return_improvement_pct=float(
                raw.get("minimum_portfolio_return_improvement_pct", 0.0)
            ),
            minimum_improved_groups=max(1, int(raw.get("minimum_improved_groups", 2))),
            maximum_group_return_regression_pct=max(
                0.0, float(raw.get("maximum_group_return_regression_pct", 5.0))
            ),
            maximum_drawdown_regression_pct=max(
                0.0, float(raw.get("maximum_drawdown_regression_pct", 5.0))
            ),
            safety_max_drawdown_pct=float(raw.get("safety_max_drawdown_pct", -40.0)),
            minimum_trade_count=max(0, int(raw.get("minimum_trade_count", 1))),
            minimum_benchmark_count=max(
                0,
                int(
                    raw.get(
                        "minimum_benchmark_count",
                        3 if raw.get("require_three_benchmarks", True) else 0,
                    )
                ),
            ),
            required_group_count=max(1, int(raw.get("required_group_count", 3))),
        )


@dataclass(frozen=True)
class PromotionDecision:
    """Serializable result of one candidate-versus-incumbent comparison."""

    passed: bool
    reasons: tuple[str, ...]
    portfolio_return_improvement_pct: float | None = None
    improved_group_count: int = 0
    compared_group_count: int = 0
    group_comparisons: dict[str, dict[str, float | bool]] = field(default_factory=dict)

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def _finite(snapshot: Mapping[str, object], key: str) -> float | None:
    try:
        value = float(snapshot[key])
    except (KeyError, TypeError, ValueError):
        return None
    return value if math.isfinite(value) else None


def compare_with_incumbent(
    candidate_by_group: Mapping[str, Mapping[str, object]],
    incumbent_by_group: Mapping[str, Mapping[str, object]],
    policy: PromotionPolicy,
) -> PromotionDecision:
    """Compare reports generated by the same unified evaluation call."""

    if not policy.enabled:
        return PromotionDecision(False, ("promotion_disabled",))
    groups = tuple(str(group) for group in candidate_by_group)
    if len(groups) != policy.required_group_count or set(groups) != set(
        incumbent_by_group
    ):
        return PromotionDecision(False, ("incomplete_group_comparison",))

    failures: list[str] = []
    comparisons: dict[str, dict[str, float | bool]] = {}
    improvements: list[float] = []
    improved_groups = 0

    for group in groups:
        candidate = candidate_by_group[group]
        incumbent = incumbent_by_group[group]
        candidate_return = _finite(candidate, "total_return")
        incumbent_return = _finite(incumbent, "total_return")
        candidate_drawdown = _finite(candidate, "max_drawdown")
        incumbent_drawdown = _finite(incumbent, "max_drawdown")
        candidate_trades = _finite(candidate, "trade_count")
        if None in (
            candidate_return,
            incumbent_return,
            candidate_drawdown,
            incumbent_drawdown,
            candidate_trades,
        ):
            failures.append(f"{group}:invalid_metrics")
            continue

        candidate_benchmarks = dict(candidate.get("benchmark_returns", {}) or {})
        incumbent_benchmarks = dict(incumbent.get("benchmark_returns", {}) or {})
        if len(candidate_benchmarks) < policy.minimum_benchmark_count:
            failures.append(f"{group}:incomplete_benchmarks")
        if set(candidate_benchmarks) != set(incumbent_benchmarks):
            failures.append(f"{group}:benchmark_contract_mismatch")
        else:
            for name in candidate_benchmarks:
                left = float(candidate_benchmarks[name])
                right = float(incumbent_benchmarks[name])
                if not math.isclose(left, right, rel_tol=0.0, abs_tol=1e-9):
                    failures.append(f"{group}:benchmark_slice_mismatch")
                    break

        improvement = float(candidate_return - incumbent_return)
        drawdown_regression = float(candidate_drawdown - incumbent_drawdown)
        improvements.append(improvement)
        improved = improvement > 0.0
        improved_groups += int(improved)
        comparisons[group] = {
            "candidate_return": float(candidate_return),
            "incumbent_return": float(incumbent_return),
            "return_improvement": improvement,
            "candidate_drawdown": float(candidate_drawdown),
            "incumbent_drawdown": float(incumbent_drawdown),
            "drawdown_regression": drawdown_regression,
            "improved": improved,
        }
        if candidate_drawdown < policy.safety_max_drawdown_pct:
            failures.append(f"{group}:safety_drawdown")
        if candidate_trades < policy.minimum_trade_count:
            failures.append(f"{group}:insufficient_trades")
        if improvement < -policy.maximum_group_return_regression_pct:
            failures.append(f"{group}:return_regression")
        if drawdown_regression < -policy.maximum_drawdown_regression_pct:
            failures.append(f"{group}:drawdown_regression")

    if len(improvements) != len(groups):
        failures.append("incomplete_valid_metrics")
        portfolio_improvement = None
    else:
        # Each market is an equal-sized independent production capital pool.
        portfolio_improvement = float(sum(improvements) / len(improvements))
        if portfolio_improvement <= policy.minimum_portfolio_return_improvement_pct:
            failures.append("insufficient_portfolio_improvement")
        if improved_groups < policy.minimum_improved_groups:
            failures.append("insufficient_improved_groups")

    return PromotionDecision(
        passed=not failures,
        reasons=tuple(dict.fromkeys(failures)),
        portfolio_return_improvement_pct=portfolio_improvement,
        improved_group_count=improved_groups,
        compared_group_count=len(improvements),
        group_comparisons=comparisons,
    )


def record_promotion_decision(
    run_id: str,
    summaries: Mapping[str, object],
    decision: PromotionDecision,
    policy: PromotionPolicy,
    *,
    incumbent_run_id: str,
    incumbent_strategy: str,
    root: Path | str = Path("data/optimizer"),
) -> None:
    """Persist evidence and expose a passed relative decision to publication.

    Raw holdout and robustness flags remain unchanged.  Only the effective
    ``eligible`` flag is promoted, with its previous absolute value retained.
    """

    base = Path(root)
    payload = decision.to_dict()
    payload.update(
        {
            "policy": asdict(policy),
            "incumbent_run_id": incumbent_run_id,
            "incumbent_strategy": incumbent_strategy,
        }
    )
    for group, summary in summaries.items():
        artifact = getattr(summary, "artifact", None)
        if not artifact or getattr(summary, "status", "") != "completed":
            continue
        path = base / "runs" / run_id / str(artifact)
        if not path.is_file():
            logger.warning(
                "Skipping promotion annotation for missing optimizer artifact: %s",
                path,
            )
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(data, dict):
            raise ValueError(f"invalid optimizer artifact: {path}")
        data["promotion"] = payload
        activation = data.get("activation", {})
        if not isinstance(activation, dict):
            activation = {}
        activation["absolute_eligible"] = bool(activation.get("eligible", False))
        activation["relative_promotion_passed"] = bool(decision.passed)
        if decision.passed:
            activation["eligible"] = True
        data["activation"] = activation
        summary_activation = getattr(summary, "activation", None)
        if isinstance(summary_activation, dict):
            summary_activation.update(activation)
        temporary = path.with_suffix(path.suffix + ".promotion.tmp")
        temporary.write_text(
            yaml.safe_dump(data, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )
        temporary.replace(path)
